#!/bin/sh

LUAROCKS_SYSCONFDIR='/etc/luarocks' exec '/usr/bin/lua5.3' \
    -e 'package.path="/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;./?.lua;./?/init.lua;/home/djangulo/.luarocks/share/lua/5.3/?.lua;/home/djangulo/.luarocks/share/lua/5.3/?/init.lua";package.cpath="/usr/local/lib/lua/5.3/?.so;/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/loadall.so;./?.so;/home/djangulo/.luarocks/lib/lua/5.3/?.so"' \
    '/usr/bin/luarocks' \
    --project-tree /home/djangulo/Documents/KCD2Mod-stoplevelling/lua_modules "$@"
